# -*- coding: utf-8 -*-
"""music_Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17EagOb1m_W8vqRwuq5U1UvGlBHz-lUtM

#Importing modules
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Mounting Gdrive"""

from google.colab import drive
drive.mount('/content/drive')

"""#Reading csv"""

df=pd.read_csv('/content/drive/My Drive/MLData/music.csv')

df

"""#Data info"""

df.shape

df.head()

df.tail()

# 1-Male,0-Female

df.describe()

"""#Data Visualization"""

count=df['genre'].value_counts()

plt.pie(count,labels=count.index,autopct='%1.1f%%')
plt.title("Music Preferences")
plt.show()

"""#Splitting IN and OUT"""

X=df.drop(columns=['genre'])
X

Y=df['genre']
Y

"""#Importing Model"""

from sklearn.tree import DecisionTreeClassifier

"""#Fitting Model"""

model=DecisionTreeClassifier()
model.fit(X,Y)

"""#Prediction"""

prediction=model.predict([[21,1],[29,0]])
prediction

"""#Model Generation with Train and Test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

model2=DecisionTreeClassifier()
model2.fit(X_train,Y_train)
prediction2=model.predict(X_test)

"""#Testing Accuracy of Model"""

from sklearn.metrics import accuracy_score
score=accuracy_score(Y_test,prediction2)
score

"""#Using Pickle for Persistent Model Use"""

import pickle as pkl
with open('music.pkl','wb') as file:
  pkl.dump(model,file)

"""#Prediction using Saved Model File"""

with open('music.pkl','rb') as file:
  load_model=pkl.load(file)

prediction3=load_model.predict([[29,0]])
prediction3

"""#Creating a visualization of tree in Graph Description Language"""

from sklearn import tree
tree.export_graphviz(model,out_file='music.dot',
                    feature_names=['age','gender'],
                    class_names=sorted(Y.unique()),
                    label='all',
                    rounded=True,
                    filled=True)

"""#Uploading tree description file to Gdrive"""

from google.colab import files
files.upload()

import shutil
shutil.move("music.dot","/content/drive/My Drive/MLData")

"""#Uploading model file to Gdrive"""

from google.colab import files
files.upload()

import shutil
shutil.move("music.pkl","/content/drive/My Drive/MLData")

